name: flutter_project
description: "A new Flutter project."

publish_to: 'none'  # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.6.1 <4.0.0"  # Set a version range for the Flutter SDK to ensure compatibility

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  audioplayers: ^6.1.0  # For playing soothing sounds
  flutter_hooks: ^0.20.5  # For smooth animations (optional)
  provider: ^6.0.5  # Optional state management for better control
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.2
  lottie: ^3.0.0
  cupertino_icons: ^1.0.8
  fl_chart: ^0.70.2
  http: ^1.3.0
  url_launcher: ^6.1.10  # Updated version
  flutter_web_auth: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/relaxing_animation.json  # Make sure the path is correct and file exists in your project
  uses-material-design: true